version: "3.8"
services:
  postgres:
    image: postgres:13-alpine
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  mongodb:
    image: 'mongo'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./env/mongo.env
  cache:
    image: 'redis:6.2-alpine'
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  service-discovery:
    build: ./service-discovery
    ports:
      - "2004:2004"
  cloud-gateway:
    build: ./cloud-gateway
    ports:
      - "2003:2003"
    depends_on:
      - service-discovery
  transaction-service:
    build: ./transaction-service
    ports:
      - "2001:2001"
    depends_on:
      - postgres
      - cloud-gateway
      - account-service
      - cache
      - rabbitmq
    env_file:
      - ./env/transaction-service.env
  account-service:
    build: ./account-service
    ports:
      - "2000:2000"
    depends_on:
      - postgres
      - cloud-gateway
      - cache
    env_file:
      - ./env/account-service.env
  customer-support-service:
    build: ./customer-support-service
    ports:
      - "2002:2002"
    depends_on:
      - mongodb
      - cloud-gateway
      - rabbitmq
    env_file:
      - ./env/customer-service.env
volumes:
  postgres-data:
  mongo-data:

















