server:
  port: 2000
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  cache:
    type: redis
    redis:
      time-to-live: 60000
  data:
    redis:
      host: cache
      port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:2004/eureka
